/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlottingPointsRouteImport } from './routes/plotting-points'
import { Route as ProjectionsRouteImport } from './routes/projections'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlottingPointsRoute = PlottingPointsRouteImport.update({
  id: '/plotting-points',
  path: '/plotting-points',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectionsRoute = ProjectionsRouteImport.update({
  id: '/projections',
  path: '/projections',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plotting-points': typeof PlottingPointsRoute
  '/projections': typeof ProjectionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plotting-points': typeof PlottingPointsRoute
  '/projections': typeof ProjectionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plotting-points': typeof PlottingPointsRoute
  '/projections': typeof ProjectionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/plotting-points' | '/projections'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/plotting-points' | '/projections'
  id: '__root__' | '/' | '/plotting-points' | '/projections'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlottingPointsRoute: typeof PlottingPointsRoute
  ProjectionsRoute: typeof ProjectionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plotting-points': {
      id: '/plotting-points'
      path: '/plotting-points'
      fullPath: '/plotting-points'
      preLoaderRoute: typeof PlottingPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projections': {
      id: '/projections'
      path: '/projections'
      fullPath: '/projections'
      preLoaderRoute: typeof ProjectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlottingPointsRoute: PlottingPointsRoute,
  ProjectionsRoute: ProjectionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
